# Generated by Django 4.2.20 on 2025-04-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='role',
            field=models.CharField(choices=[('Maintenance', 'Maintenance'), ('Transport', 'Transport'), ('Mess', 'Mess'), ('Other', 'Other')], default='User', max_length=20),
        ),
    ]
