# Generated by Django 5.1.7 on 2025-04-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_authority_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
