# Generated by Django 5.1.7 on 2025-04-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_upvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('accommodation', 'Accommodation'), ('mess', 'Mess & Food'), ('maintenance', 'Maintenance'), ('safety', 'Safety & Security'), ('technical', 'Technical (Wi-Fi, Electricity, etc.)'), ('billing', 'Billing & Payments'), ('noise', 'Noise & Disturbance'), ('staff', 'Staff Behavior'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
