# Generated by Django 5.1.7 on 2025-04-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaint_complaint_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='user_confirmation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
