# Generated by Django 5.1.7 on 2025-04-11 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_assigned_authority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at']},
        ),
    ]
