# Generated by Django 5.1.7 on 2025-04-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_user_confirmation_status'),
        ('complaints', '0006_alter_complaint_options'),
    ]

    operations = [
    ]
