# Generated by Django 5.1.7 on 2025-04-13 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_merge_20250413_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='user_confirmation_status',
        ),
    ]
