# Generated by Django 5.1.7 on 2025-04-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_remove_complaint_user_confirmation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('Transport', 'Transport'), ('Mess', 'Mess'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], default='general', max_length=30),
        ),
    ]
